---
title: "Naive Model"
output: pdf_document
---

```{r}
library(dplyr)
library(cmdstanr)
library(ggplot2)
```

First, lets import the data and prep it to be fed into the stan model.
```{r}
data_processed = read.csv("../data/processed/oasis_processed.csv")

# selecting relevant columns and enforcing feature constraints
data <- data_processed %>%
  select(sex_male, Age, nWBV, Educ, CDR_binary) %>%
  filter(Educ > 1,
         Educ < 5,
         Age > 0,
         nWBV > 0,
         (sex_male == 1 | sex_male == 0),
         (CDR_binary == 1 | CDR_binary == 0)
         )

# creating the data object to be passed into stan
stan_data <- list(
  N = nrow(data),
  sex_male = data$sex_male,
  age = data$Age,
  brain_vol = data$nWBV,
  educ = data$Educ,
  CDR_binary = data$CDR_binary
)
```

Next, lets retrieve the naive model from the stan file and fit it.
```{r}
# get stan model
naive_model <- cmdstan_model("naive_model.stan")

fit <- naive_model$sample(
  seed = 405,
  data = stan_data,
  chains = 4,
  iter_sampling = 2500,
  show_messages = FALSE
)

fit$print()
fit$summary()
```
Let's perform a goodness of fit check on the naive model.
```{r}
ci_limits = matrix(0, nrow = nrow(data), ncol = 2)

# extract probabilities from fitted model object
draws_df <- fit$draws(format = "df")
p_cols <- grep("^p_pred\\[", names(draws_df), value = TRUE)
p_matrix <- as.matrix(draws_df[, p_cols])
p_mean <- colMeans(p_matrix)

# calculate credible intervals
for (i in 1:nrow(data)) {
  cred_int <- quantile(p_matrix[, i], c(0.1, 0.9))
  ci_limits[i, 1] <- cred_int[1]
  ci_limits[i, 2] <- cred_int[2]
}
```

```{r}
calibration <- data.frame(
  y_true = data$CDR_binary,
  p = p_mean
) %>%
  mutate(bins = ntile(p, 15)) %>%
  group_by(bins) %>%
  summarise(
    mean_pred = mean(p),
    mean_true = mean(y_true)
  )

ggplot(calibration, aes(x = mean_pred, y = mean_true)) +
  geom_point() +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  theme_minimal() +
  xlab("Mean Predicted Probability") + 
  ylab("Mean True Value (Diagnosis)") +
  ggtitle("Calibration Plot")
```
As we can see, the plot is not very calibrated.  Therefore, we should try standardizing the numeric predictors to see if we get a better result.